tplProjectName: mobilebuilder_tpl_7_9_0
â†“Menu [mobile.components.UIDynamicMenu-1604074900896]: ğŸ— mobileMenus/Menu.yaml
â†“VonageVideo [mobile.components.UISharedComponent-1604074988538]: ğŸ— mobileSharedComponents/VonageVideo.yaml
â†“SessionsPage [mobile.components.PageComponent-1604074906869]: ğŸ— mobilePages/SessionsPage.yaml
â†“VideoPagePublish [mobile.components.PageComponent-1604828089911]: ğŸ— mobilePages/VideoPagePublish.yaml
â†“VideoPageSubscribe [mobile.components.PageComponent-1604935551023]: ğŸ— mobilePages/VideoPageSubscribe.yaml
â†“AskSessionPage [mobile.components.PageComponent-1604829479954]: ğŸ— mobilePages/AskSessionPage.yaml