tplProjectName: mobilebuilder_tpl_7_9_0
â†“Menu [mobile.components.UIDynamicMenu-1604074900896]: ğŸ— mobileMenus/Menu.yaml
â†“SharedAction [mobile.components.UIActionStack-1620306204531]: ğŸ— mobileSharedActions/SharedAction.yaml
â†“initAndCreate [mobile.components.UIActionStack-1620306642547]: ğŸ— mobileSharedActions/initAndCreate.yaml
â†“initOpenTok [mobile.components.UIActionStack-1620306731231]: ğŸ— mobileSharedActions/initOpenTok.yaml
â†“modalVideoCall [mobile.components.UIActionStack-1620307352727]: ğŸ— mobileSharedActions/modalVideoCall.yaml
â†“disconnectFromSession [mobile.components.UIActionStack-1620744198968]: ğŸ— mobileSharedActions/disconnectFromSession.yaml
â†“VonageVideo [mobile.components.UISharedComponent-1604074988538]: ğŸ— mobileSharedComponents/VonageVideo.yaml
â†“SessionsPage [mobile.components.PageComponent-1604074906869]: ğŸ— mobilePages/SessionsPage.yaml
â†“VideoPagePublish [mobile.components.PageComponent-1604828089911]: ğŸ— mobilePages/VideoPagePublish.yaml
â†“VideoPageSubscribe [mobile.components.PageComponent-1604935551023]: ğŸ— mobilePages/VideoPageSubscribe.yaml
â†“AskSessionPage [mobile.components.PageComponent-1604829479954]: ğŸ— mobilePages/AskSessionPage.yaml
â†“Page [mobile.components.PageComponent-1620308534347]: ğŸ— mobilePages/Page.yaml